FROM python:3.6.1

# set working directory
RUN mkdir -p /usr/src/
WORKDIR /usr/src/

# add requirements (to leverage Docker cache)
ADD ./requirements.txt /usr/src/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# run server
CMD python manage.py runserver -h 0.0.0.0
