FROM python:3.6.1

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/
WORKDIR /usr/src/

# add requirements (to leverage Docker cache)
ADD ./requirements.txt /usr/src/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
ADD . /usr/src/

# run server
CMD gunicorn -b 0.0.0.0:5000 ./src
